remote_theme: "jekyll/minima@93b1921"
minima:
  nav_pages:
    - README.md
    - AUDITORIUM.md
    - AUDITORIUM_V2.md
  skin: solarized
  site:
    title: ODDSOCKMACHINE
  description: The Art and Engineering of Dave Walker
  author: "Dave Walker"